[package]
name = "exifrename"
version = "0.1.0"
edition = "2021"
authors = ["Chris Down <chris@chrisdown.name>"]
description = "Rename or copy files based on EXIF data."
homepage = "https://github.com/cdown/exifrename"
readme = "README.md"
keywords = ["exif", "image", "rename", "organise", "organize"]
license = "MIT"

[dependencies]
anyhow = "1.0.69"
clap = { version = "4.1.6", features = ["derive"] }
hashbrown = "0.13.2"
kamadak-exif = "0.5.5"
tempfile = "3.4.0"

[target.'cfg(target_family = "unix")'.dependencies]
libc = "0.2.139"

[target.'cfg(target_family = "windows")'.dependencies]
winapi = "0.3.9"
