[package]
name = "exifrename"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
clap = { version = "4.1.6", features = ["derive"] }
hashbrown = "0.13.2"
kamadak-exif = "0.5.5"
libc = "0.2.139"
tempfile = "3.3.0"
