[package]
name = "exifrename"
version = "0.2.0"
edition = "2021"
authors = ["Chris Down <chris@chrisdown.name>"]
description = "Rename or copy files based on EXIF data."
repository = "https://github.com/cdown/exifrename"
readme = "README.md"
keywords = ["exif", "image", "rename", "organise", "organize"]
categories = ["command-line-utilities", "filesystem"]
license = "MIT"

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.2.1", features = ["derive"] }
kamadak-exif = "0.5.5"
lazy_static = "1.4.0"
tempfile = "3.5.0"
ftempl = { path = "/home/cdown/git/func_template" }

[target.'cfg(target_family = "unix")'.dependencies]
libc = "0.2.140"

[target.'cfg(target_family = "windows")'.dependencies]
winapi = { version = "0.3.9", features = ["winerror"] }
